# DS321: Computational Statistics <br>

##   Laboratory Exercise: Univariate (Secant Method) and Multivariate Optimization (Introduction)

University of Science and Technology of Southern Philippines <br>

## Student Name: <code>Joear T. Berdon</code>


Instructor: **Romen Samuel Wabina, MSc** <br>
MSc Data Science and AI | Asian Institute of Technology <br>
*ongoing* PhD Data Science (Healthcare and Clinical Informatics) 


### Instructions
- Please submit this laboratory exercise as a **Jupyter Notebook file** <code>.ipynb</code> via email <code>romensamuelrodis.wab@student.mahidol.edu</code>
- Always remember: I use GPTZero 

### <code>Question 1</code>: Modify the function <code>secant_method</code> by adding the tolerance value as a parameter in the function. Use the function to evaluate whether its number of iterations has decreased. 

In [1]:
import math

Taking $f(x) = 2x^3 - x^2 +10x - 3 $ at initial values $x_0 = 2$ and $x_1 = 4$ with $tol=1e-6$, $max iterations = 10$ as an example.

In [2]:
#setting the globals
A = 2
B = 4
TOL = 10**-6
N = 10

#defining function
def f(x):
    return (2*math.pow(x,3)) - math.pow(x,2) + (10*x) - 3

#secant method implementation
def secant_method(f, x0, x1, tol, max_iter):
    
    for i in range(0,max_iter):
        
        #checks if the second term is undefined (zero denominator)
        if f(x1) - f(x0) == 0:
            print("Error!")
            break
            
        #Calculation
        x2 = x1 - (f(x1) * (x1 - x0)) / float(f(x1) - f(x0))
            
        #Decide to repeat the steps 
        if abs(x2 - x1) < tol:
            return x2
        
        print(f'Iteration {i+1}: \t {x2}')
        
        #updating
        x0 = x1
        x1 = x2
        
    return "The method failed after {} iterations".format(N) 

#calling the method
root = secant_method(f, A, B, TOL, N)
print("Secant's method local optima: x = ", root)

Iteration 1: 	 1.5166666666666666
Iteration 2: 	 1.200154503032644
Iteration 3: 	 0.6014833604425738
Iteration 4: 	 0.36834378672672496
Iteration 5: 	 0.3064694836838134
Iteration 6: 	 0.303638291005812
Iteration 7: 	 0.30362066994048525
Secant's method local optima: x =  0.3036206657641235


After setting the **tolerance as a parameter** in the function, the number of iterations has decreased. It is because it satisfies the condition in which it will give <code>local optima if it's less than tolerance</code> rather than running all iterations. 

### <code>Question 2</code>: Evaluate the following equations on Secant method at 10 iterations using your modified Python function.
- $f(x) = x^3 - x - 1$ at initial values $x_0 = 1$ and $x_1 = 2$.
- $f(x) = \cos{x} + 2\sin{x} + x^2$ at initial values $x_0 = 0.001$ and $x_1 = 0.001$.

**1.** $f(x) = x^3 - x - 1$ at initial values $x_0 = 1$ and $x_1 = 2$.

In [3]:
#setting the globals
A = 1
B = 2
TOL = 10**-6
N = 10

#defining function
def f(x):
    return math.pow(x,3) - x - 1

#secant method implementation
def secant_method(f, x0, x1, tol, max_iter):
    
    for i in range(0,max_iter):
        
        #checks if the second term is undefined (zero denominator)
        if f(x1) - f(x0) == 0:
            print("Error!")
            break
            
        #Calculation
        x2 = x1 - (f(x1) * (x1 - x0)) / float(f(x1) - f(x0))
            
        #Decide to repeat the steps 
        if abs(x2 - x1) < tol:
            return x2
        
        print(f'Iteration {i+1}: \t {x2}')
        
        #updating
        x0 = x1
        x1 = x2
        
    return "The method failed after {} iterations".format(N) 

#calling the method
root = secant_method(f, A, B, TOL, N)
print("Secant's method local optima: x = ", root)

Iteration 1: 	 1.1666666666666665
Iteration 2: 	 1.2531120331950207
Iteration 3: 	 1.3372064458416564
Iteration 4: 	 1.323850096387641
Iteration 5: 	 1.324707936532088
Iteration 6: 	 1.3247179653538177
Secant's method local optima: x =  1.3247179572446703


**2.** $f(x) = \cos{x} + 2\sin{x} + x^2$ at initial values $x_0 = 0.001$ and $x_1 = 0.001$.

In [4]:
#setting the globals
A = 0.001
B = 0.001
TOL = 10**-6
N = 10

#defining function
def f(x):
    return math.cos(x) - 2*math.sin(x) + math.pow(x,2)

#secant method implementation
def secant_method(f, x0, x1, tol, max_iter):
    
    for i in range(0,max_iter):
        
        #checks if the second term is undefined (zero denominator)
        if f(x1) - f(x0) == 0:
            print("Error!")
            break
            
        #Calculation
        x2 = x1 - (f(x1) * (x1 - x0)) / float(f(x1) - f(x0))
            
        #Decide to repeat the steps 
        if abs(x2 - x1) < tol:
            return x2
        
        print(f'Iteration {i+1}: \t {x2}')
        
        #updating
        x0 = x1
        x1 = x2
        
    return "The method failed after {} iterations".format(N) 

#calling the method
root = secant_method(f, A, B, TOL, N)
print("Secant's method local optima: x = ", root)

Error!
Secant's method local optima: x =  The method failed after 10 iterations


It will give an error kasi by solving the second term in the secant method, it's <code>denominator is equal to zero </code> resulting to undefined hence, it will not give local optima.

### <code>Question 3</code>: Evaluate the following equations on Secant and Newton's method at 10 iterations. Create a function that prints the local optima of both methods and measure their difference. You can use the functions above. 
- $f(x) = x^2 - 2$ where $x_0 = 2$ as the initial guess for Newton's Method while $x_0 = 3$ and $x_1 = 2$ for the Secant Method
- $f(x) = x^3 - 7x^2 + 8x - 3$ where $x_0 = 0.45$ as the initial guess for Newton's method while $x_0 = 1$ and $x_1 = 0.45$ for the Secant Method

**1.** $f(x) = x^2 - 2$ where $x_0 = 2$ as the initial guess for Newton's Method while $x_0 = 3$ and $x_1 = 2$ for the Secant Method

In [5]:
#function definition
def f(x):
    return math.pow(x,2)-2

#first derivative
def fprime(x):
    return (2 * x)

#newtons implementation
def newton(approx, max_iter):
    a = approx
    
    for i in range(0, max_iter):
        
        #computation
        y = f(a)/fprime(a)
        b = a - y
        
        #checks if it has zero derivative
        if fprime(a) == 0:
            print("Error! f'(x) is undefined, no root found!")
            break
            
        #updating
        a = b
        print(f'Iteration {i+1}: \t {b}')
    return b

#secant method implementation
def secant_method(f, x0, x1, max_iter):
    
    for i in range(0,max_iter):
        
        #checks if the second term is undefined (zero denominator)
        if f(x1) - f(x0) == 0:
            print("Error!")
            break
            
        #Calculation
        x2 = x1 - (f(x1) * (x1 - x0)) / float(f(x1) - f(x0))
             
        #updating
        x0 = x1
        x1 = x2
        
        print(f'Iteration {i+1}: \t {x2}')
    return x2

def difference():
    a= newton_root
    b = secant_root
    diff = abs(newton_root - secant_root)
    return diff

In [6]:
#calling the method for newton
newton_root = newton(2, 10)
print("Newton's method local optima: x = ", newton_root)

Iteration 1: 	 1.5
Iteration 2: 	 1.4166666666666667
Iteration 3: 	 1.4142156862745099
Iteration 4: 	 1.4142135623746899
Iteration 5: 	 1.4142135623730951
Iteration 6: 	 1.414213562373095
Iteration 7: 	 1.4142135623730951
Iteration 8: 	 1.414213562373095
Iteration 9: 	 1.4142135623730951
Iteration 10: 	 1.414213562373095
Newton's method local optima: x =  1.414213562373095


In [7]:
#calling the method for secant
secant_root = secant_method(f, 3, 2, 10)
print("Secant's method local optima: x = ", secant_root)

Iteration 1: 	 1.6
Iteration 2: 	 1.4444444444444444
Iteration 3: 	 1.416058394160584
Iteration 4: 	 1.414233059257159
Iteration 5: 	 1.4142135750814935
Iteration 6: 	 1.4142135623731826
Iteration 7: 	 1.414213562373095
Iteration 8: 	 1.4142135623730951
Iteration 9: 	 1.414213562373095
Iteration 10: 	 1.414213562373095
Secant's method local optima: x =  1.414213562373095


In [8]:
D = difference()
print("Newton's Method local optima: ", newton_root)
print("Secant Method local optima: ", secant_root)
print("Difference: ", D)

Newton's Method local optima:  1.414213562373095
Secant Method local optima:  1.414213562373095
Difference:  0.0


**2.** $f(x) = x^3 - 7x^2 + 8x - 3$ where $x_0 = 0.45$ as the initial guess for Newton's method while $x_0 = 1$ and $x_1 = 0.45$ for the Secant Method

In [9]:
#function definition
def f(x):
    return math.pow(x,3) - 7*math.pow(x,2) + 8*x - 3

#first derivative
def fprime(x):
    return 3 * math.pow(x,2) - (14 * x) + 8

#newtons implementation
def newton(approx, max_iter):
    a = approx
    
    for i in range(0, max_iter):
        
        #computation
        y = f(a)/fprime(a)
        b = a - y
        
        #checks if it has zero derivative
        if fprime(a) == 0:
            print("Error! f'(x) is undefined, no root found!")
            break
            
        #updating
        a = b
        print(f'Iteration {i+1}: \t {b}')
    return b

#secant method implementation
def secant_method(f, x0, x1, max_iter):
    
    for i in range(0,max_iter):
        
        #checks if the second term is undefined (zero denominator)
        if f(x1) - f(x0) == 0:
            print("Error!")
            break
            
        #Calculation
        x2 = x1 - (f(x1) * (x1 - x0)) / float(f(x1) - f(x0))
             
        #updating
        x0, x1 = x1, x2
        
        print(f'Iteration {i+1}: \t {x2}')
    return x2

def difference():
    a= newton_root
    b = secant_root
    diff = abs(newton_root - secant_root)
    return diff

In [10]:
#calling the method for newton
newton_root = newton(0.45, 10)
print("Newton's method local optima: x = ", newton_root)

Iteration 1: 	 0.7647887323943662
Iteration 2: 	 0.2096527279903404
Iteration 3: 	 0.5216267176184952
Iteration 4: 	 0.911261310664203
Iteration 5: 	 0.5732987502857287
Iteration 6: 	 1.1211897712246115
Iteration 7: 	 0.7593116146928851
Iteration 8: 	 0.17798419674703692
Iteration 9: 	 0.49784048712938106
Iteration 10: 	 0.8523426445442217
Newton's method local optima: x =  0.8523426445442217


In [11]:
#calling the method for secant
secant_root = secant_method(f, 1, 0.45, 10)
print("Secant's method local optima: x = ", secant_root)

Iteration 1: 	 -1.0100502512562815
Iteration 2: 	 0.5072465811609521
Iteration 3: 	 0.557113720492756
Iteration 4: 	 0.9449021363844228
Iteration 5: 	 -0.13481905240473768
Iteration 6: 	 1.2169884993018618
Iteration 7: 	 2.2562543492733096
Iteration 8: 	 0.9555083622238383
Iteration 9: 	 0.8171942165462645
Iteration 10: 	 0.5283409088722151
Secant's method local optima: x =  0.5283409088722151


In [12]:
D = difference()
print("Newton's Method local optima: ", newton_root)
print("Secant Method local optima: ", secant_root)
print("Difference: ", D)

Newton's Method local optima:  0.8523426445442217
Secant Method local optima:  0.5283409088722151
Difference:  0.32400173567200663


## Multivariate Optimization

Using the function <code>get_critical_points</code>, evaluate the following functions below by classifying the critical points whether they are local minima, local maxima, saddle points, or the function is inconclusive. You can create a Python function to solve this.
- $f(x,y) = x^2+2xy+4y^2+5x-6y$
- $f(x,y) = -x^2 - y^2$
- $f(a, b) = a^2 + 3a^2 - 9a + b^2 - 12b$
- $f(r, s) = 3rs - r^2 - s^2$
- $f(c, d) = x^2 + y^2 + 2x + 6y$

In [13]:
import numpy as np
import sympy

- $f(x,y) = x^2+2xy+4y^2+5x-6y$

In [14]:
#defining the variables
x, y = sympy.symbols('x, y')

#function
f = x**2 + (2*x*y) + (4*y**2) + 5*x - 6*y

def get_critical_points(f, variables):
    
    #this is where we get the partial derivatives of the function (f) with respect to each variable in (variables) 
    df = [sympy.diff(f, x) for x in variables]

    #hessian matrix
    H = np.array([[sympy.diff(df[i], x) for x in variables] for i in range(len(variables))])
    H = H.astype('float')
    
    #solving critical point
    crit_points = sympy.solve(df, variables)
    
    #solving determinant
    determinant = np.linalg.det(H)
    
    #classification
    if determinant > 0 and H[0,0] > 0:
        return crit_points, H, determinant, H[0,0], "Local Minimum"
    elif determinant > 0 and H[0,0] < 0:
        return crit_points, H, determinant, H[0,0], "Local Maximum"
    elif determinant == 0:
        return crit_points, H, determinant, H[0,0], "Inconclusive"
    else:
        return crit_points, H, determinant, H[0,0], "Saddle point"


#calling the method
critical_point, Hessian, det, fxx, classification = get_critical_points(f, [x, y])

print(f"Critical point: {critical_point}\nHessian Matrix:\n {Hessian} \nDeterminant: {det} \nf_xx: {fxx} \nClassification: {classification} \n") 


Critical point: {x: -13/3, y: 11/6}
Hessian Matrix:
 [[2. 2.]
 [2. 8.]] 
Determinant: 12.0 
f_xx: 2.0 
Classification: Local Minimum 



- $f(x,y) = -x^2 - y^2$

In [15]:
#defining the variables
x, y = sympy.symbols('x, y')

#function
f = (-x**2) - (y**2)

def get_critical_points(f, variables):
    
    #this is where we get the partial derivatives of the function (f) with respect to each variable in (variables) 
    df = [sympy.diff(f, x) for x in variables]

    #hessian matrix
    H = np.array([[sympy.diff(df[i], x) for x in variables] for i in range(len(variables))])
    H = H.astype('float')
    
    #solving critical point
    crit_points = sympy.solve(df, variables)
    
    #solving determinant
    determinant = np.linalg.det(H)
    
    #classification
    if determinant > 0 and H[0,0] > 0:
        return crit_points, H, determinant, H[0,0], "Local Minimum"
    elif determinant > 0 and H[0,0] < 0:
        return crit_points, H, determinant, H[0,0], "Local Maximum"
    elif determinant == 0:
        return crit_points, H, determinant, H[0,0], "Inconclusive"
    else:
        return crit_points, H, determinant, H[0,0], "Saddle point"

#calling the method
critical_point, Hessian, det, fxx, classification = get_critical_points(f, [x, y])

print(f"Critical point: {critical_point}\nHessian Matrix:\n {Hessian} \nDeterminant: {det} \nf_xx: {fxx} \nClassification: {classification} \n") 


Critical point: {x: 0, y: 0}
Hessian Matrix:
 [[-2.  0.]
 [ 0. -2.]] 
Determinant: 4.0 
f_xx: -2.0 
Classification: Local Maximum 



- $f(a, b) = a^2 + 3a^2 - 9a + b^2 - 12b$

In [16]:
#defining the variables
a, b = sympy.symbols('x, y')

#function
f = x**2 +(3*x**2) - 9*x + y**2 - 12*y

def get_critical_points(f, variables):
    
    #this is where we get the partial derivatives of the function (f) with respect to each variable in (variables) 
    df = [sympy.diff(f, x) for x in variables]

    #hessian matrix
    H = np.array([[sympy.diff(df[i], x) for x in variables] for i in range(len(variables))])
    H = H.astype('float')
    
    #solving critical point
    crit_points = sympy.solve(df, variables)
    
    #solving determinant
    determinant = np.linalg.det(H)
    
    #classification
    if determinant > 0 and H[0,0] > 0:
        return crit_points, H, determinant, H[0,0], "Local Minimum"
    elif determinant > 0 and H[0,0] < 0:
        return crit_points, H, determinant, H[0,0], "Local Maximum"
    elif determinant == 0:
        return crit_points, H, determinant, H[0,0], "Inconclusive"
    else:
        return crit_points, H, determinant, H[0,0], "Saddle point"

#calling the method
critical_point, Hessian, det, fxx, classification = get_critical_points(f, [x, y])

print(f"Critical point: {critical_point}\nHessian Matrix:\n {Hessian} \nDeterminant: {det} \nf_xx: {fxx} \nClassification: {classification} \n") 


Critical point: {x: 9/8, y: 6}
Hessian Matrix:
 [[8. 0.]
 [0. 2.]] 
Determinant: 15.999999999999998 
f_xx: 8.0 
Classification: Local Minimum 



- $f(r, s) = 3rs - r^2 - s^2$

In [19]:
#defining the variables
x, y = sympy.symbols('r, s')

#function
f = 3*r*s - r**2 - s**2

def get_critical_points(f, variables):
    
    #this is where we get the partial derivatives of the function (f) with respect to each variable in (variables) 
    df = [sympy.diff(f, x) for x in variables]

    #hessian matrix
    H = np.array([[sympy.diff(df[i], x) for x in variables] for i in range(len(variables))])
    H = H.astype('float')
    
    #solving critical point
    crit_points = sympy.solve(df, variables)
    
    #solving determinant
    determinant = np.linalg.det(H)
    
    #classification
    if determinant > 0 and H[0,0] > 0:
        return crit_points, H, determinant, H[0,0], "Local Minimum"
    elif determinant > 0 and H[0,0] < 0:
        return crit_points, H, determinant, H[0,0], "Local Maximum"
    elif determinant == 0:
        return crit_points, H, determinant, H[0,0], "Inconclusive"
    else:
        return crit_points, H, determinant, H[0,0], "Saddle point"

#calling the method
critical_point, Hessian, det, fxx, classification = get_critical_points(f, [x, y])

print(f"Critical point: {critical_point}\nHessian Matrix:\n {Hessian} \nDeterminant: {det} \nf_xx: {fxx} \nClassification: {classification} \n") 


Critical point: {r: 0, s: 0}
Hessian Matrix:
 [[-2.  3.]
 [ 3. -2.]] 
Determinant: -5.000000000000001 
f_xx: -2.0 
Classification: Saddle point 



- $f(c, d) = x^2 + y^2 + 2x + 6y$

In [22]:
#defining the variables
x, y = sympy.symbols('x, y')

#function
f = x**2 + y**2 + 2*x + 6*y

def get_critical_points(f, variables):
    
    #this is where we get the partial derivatives of the function (f) with respect to each variable in (variables) 
    df = [sympy.diff(f, x) for x in variables]

    #hessian matrix
    H = np.array([[sympy.diff(df[i], x) for x in variables] for i in range(len(variables))])
    H = H.astype('float')
    
    #solving critical point
    crit_points = sympy.solve(df, variables)
    
    #solving determinant
    determinant = np.linalg.det(H)
    
    #classification
    if determinant > 0 and H[0,0] > 0:
        return crit_points, H, determinant, H[0,0], "Local Minimum"
    elif determinant > 0 and H[0,0] < 0:
        return crit_points, H, determinant, H[0,0], "Local Maximum"
    elif determinant == 0:
        return crit_points, H, determinant, H[0,0], "Inconclusive"
    else:
        return crit_points, H, determinant, H[0,0], "Saddle point"

#calling the method
critical_point, Hessian, det, fxx, classification = get_critical_points(f, [x, y])

print(f"Critical point: {critical_point}\nHessian Matrix:\n {Hessian} \nDeterminant: {det} \nf_xx: {fxx} \nClassification: {classification} \n") 


Critical point: {x: -1, y: -3}
Hessian Matrix:
 [[2. 0.]
 [0. 2.]] 
Determinant: 4.0 
f_xx: 2.0 
Classification: Local Minimum 

